FROM openjdk:11
RUN mkdir -p /data/project
ADD user-service-1.0-SNAPSHOT.jar /data/project/user-service-1.0-SNAPSHOT.jar
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
EXPOSE 8081
ENTRYPOINT ["/bin/sh", "-c", "java -jar /data/project/user-service-1.0-SNAPSHOT.jar"]

