#server:
#  port: 8081
#spring:
#  application:
#    name: user-service
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://${net.db.host}:3306/NetChunky?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${net.db.username}
#    password: ${net.db.password}
#mybatis-plus:
#  configuration:
#    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: ASSIGN_ID
#logging:
#  level:
#    com.net.com.net.user: debug