spring:
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: 872919781@qq.com
    password: soysbwknrbozbeaa
    test-connection: false
    properties:
      mail:
        debug: false
        smtp:
          auth: false
        mime:
          splitlongparameters: false
    default-encoding: UTF-8
properties:
  set:
    login: "email:code:login:"
    register: "email:code:register:"